name: DockerHub Publish

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    
    - name: build and release to DockerHub
      env:
        REPOSITORY: oortuniv/timescaledb
      run: |
        docker build -t $REPOSITORY .
        docker tag $REPOSITORY:latest $REPOSITORY:$GITHUB_REF_NAME
        docker push $REPOSITORY --all-tags

    - name: uplaod Dockerhub readme
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        repository: oortuniv/timescaledb
        readme-filepath: README.md
        short-description: ${{github.event.repository.description}}
